name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Upload to NIployments register
      uses: NIAEFEUP/push-to-niployments@v2.2
      with:
        docker_dockerfile: dockerfiles/Dockerfile.website
        docker_context: .
        docker_target: deploy
        docker_build_args: |
          LARAVEL_ENV=${{ vars.LARAVEL_ENV }}
          LARAVEL_ENV_FILE=${{ vars.LARAVEL_ENV_FILE }}
          LARAVEL_ENV_FILE_KEY=${{ secrets.LARAVEL_ENV_FILE_KEY }}
        NIPLOYMENTS_REGISTRY_URL: ${{ vars.NIPLOYMENTS_REGISTRY_URL }}
        NIPLOYMENTS_REGISTRY_USERNAME: ${{ vars.NIPLOYMENTS_REGISTRY_USERNAME }}
        NIPLOYMENTS_REGISTRY_PASSWORD: ${{ secrets.NIPLOYMENTS_REGISTRY_PASSWORD }}
